name: Build and Deploy Demos
on:
  push:
    branches:
      - sc-79849-implement-improved-demo-build-pipeline

jobs:
  build:
    uses: ./.github/workflows/build-demos.yml
    with:
      branch: ${{ github.ref }}
      demo-names: 'covalent_cloud_gpu gbs'

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-demos.yml
    with:
      environment: swc-dev
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      preview: false
      branch: ${{ github.ref }}
    secrets: inherit
