# AC:
# - v2_build_demos workflow runs when a commit is pushed to a pull request
# - Only changed/added demos should be built on a commit
# - Changed demos are deployed as previews
# - PRs targeting the dev branch use development dependencies
# - PRs targeting master use the stable dependencies (constraints.txt)

#  We want to create a Workflow that runs on pull requests to the dev branch and master branch
# depending on if the branch is dev or master, we want to use different dependencies
# we want to use the stable dependencies for master and the development dependencies for dev, so we will need to check the branch being targeted and determine which dependencies to use. The workflow "Build V2 Demos" has a bool variable for this

name: Build V2 Demos on Pull Request

on:
  pull_request:
    branches: [master, dev]
    # Runs on pull requests where the target branch is dev or master

concurrency:
  group: build-v2-demos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set_build_params:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Changed Demos
        run: echo "I will eventually get the changed demos"

      - name: Make and echo saying dev requirements
        run: echo "I will run the dev requirements"
        if: github.event.pull_request.base.ref == 'dev'
      
      - name: Make and echo saying master requirements
        run: echo "I will run the master requirements"
        if: github.event.pull_request.base.ref == 'master'
        
