name: Build demos
on:
  workflow_call:
    inputs:
      branch:
        description: The QML branch to checkout and build demos for
        required: true
        type: string
      demo-names:
        description: |
          Instead of building all demos, only build the demos specified in this list.
        required: false
        type: string
        default: ''
    outputs:
      artifact-name:
        description: "Name of the artifact containing the built demos"
        value: ${{ jobs.build-demos.outputs.artifact-name }}

jobs:
  build-demos:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.artifact-name.outputs.artifact-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install QML app
        run: pip install .

      - name: Build demos
        run: |
          qml build \
            --execute \
            --format json \
            ${{ inputs.demo-names }}

      - name: Get artifact name
        id: artifact-name
        run: echo "artifact-name=demo-build-${{ github.sha }}" >> $GITHUB_ENV
      
      - name: Upload artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.artifact-name }}
          path: _build/pack/*.zip
          retention-days: 1
