name: Build and Deploy Demos
on:
  push:
    branches:
      - sc-81925-qml-repository-ci-pushes-newly-built-demos

jobs:
  build:
    uses: ./.github/workflows/build-demos.yml
    with:
      branch: ${{ github.ref }}
      demo-names: 'tutorial_diffable_shadows covalent_cloud_gpu tutorial_barren_gadgets'

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-demos.yml
    with:
      environment: dev
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      preview: false
      branch: ${{ github.ref}}
    secrets: inherit
