name: Build V2 Demos on Pull Request

on:
  pull_request:
    branches: [master, dev]

concurrency:
  group: build-v2-demos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if PR is a fork
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "This workflow does not run on forks, and requires a review before being merged into a branch for testing and secondary or final review."
          exit 1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List workspace contents
        run: ls -R .github

      - name: Get Changed Demos
        id: changed-demos
        uses: ./.github/actions/get-changed-demos
        with:
          json: true
      
      - name: Build V2 Demos
        uses: ./.github/workflows/v2-build-demos.yml
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          demo-names: ${{ steps.changed-demos.outputs.changed-demos }}
          dev: ${{ github.event.pull_request.base.ref == 'dev' }}
          save-artifact: true
          artifact-name: demo-build-${{ github.event.pull_request.head.sha }}
          keep-going: false
          quiet: false
          batch_size: 10

      - name: Deploy
        run: |
          echo "Deploying demos..."