name: Build and Deploy V2 Demo Previews on Pull Requests
on:
  pull_request:
    branches: [master, dev]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: build-v2-demos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is a fork
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "Skipping workflow for forked PRs"
          exit 1
  
  identify-changed-demos:
    runs-on: ubuntu-latest
    needs: validate-pr-source
    outputs:
      updated: ${{ steps.get-changed-demos.outputs.updated }}
      deleted: ${{ steps.get-changed-demos.outputs.deleted }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Changed Demos
        id: get-changed-demos
        uses: ./.github/actions/get-changed-demos
      
      - name: Output Changed Demos
        run: |
          echo "Updated Demos: ${{ steps.get-changed-demos.outputs.updated }}"
          echo "Deleted Demos: ${{ steps.get-changed-demos.outputs.deleted }}"

  build-updated-demos:
    uses: ./.github/workflows/v2-build-demos.yml
    needs: identify-changed-demos
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      demo-names: ${{ needs.identify-changed-demos.outputs.updated }}
      dev: ${{ github.event.pull_request.base.ref == 'dev' }}
      save-artifact: true
      artifact-name: demo-build-${{ github.event.pull_request.head.sha }}
      keep-going: false
      quiet: false
      batch_size: 10

  deploy-preview-demos:
    uses: ./.github/workflows/v2-deploy-demos.yml
    needs: build-updated-demos
    with:
      environment: 'swc-staging' ## In a subsequent PR, this should be changed to the appropriate environment that internal and third parties can access
      artifact-name: demo-build-${{ github.event.pull_request.head.sha }}
      preview: true
      branch: ${{ github.event.pull_request.head.ref }}
    secrets: inherit

# TODOS: In subsequent PRs, the following should be added:
  # 1. Add a step to determine the SWC environment to deploy to (Always prod?)
  # 2. Add a step to post a comment on the PR with the preview URL.
  # 3. Determine whether or not we can/want to delete demos.
