# AC:
# - v2_build_demos workflow runs when a commit is pushed to a pull request
# - Only changed/added demos should be built on a commit
# - Changed demos are deployed as previews
# - PRs targeting the dev branch use development dependencies
# - PRs targeting master use the stable dependencies (constraints.txt)

#  We want to create a Workflow that runs on pull requests to the dev branch and master branch
# depending on if the branch is dev or master, we want to use different dependencies
# we want to use the stable dependencies for master and the development dependencies for dev, so we will need to check the branch being targeted and determine which dependencies to use. The workflow "Build V2 Demos" has a bool variable for this

name: Build V2 Demos on Pull Request

on:
  pull_request:
    branches: [master, dev]
    # Runs on pull requests where the target branch is dev or master

concurrency:
  group: build-v2-demos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # If a PR is a fork, we need do not run the workflow, all external demo submissions
      # should be done via fork but require a review before merged into a branch for testing and secondary review/ a final review.cancel-timeout-minutes: 
      
      # Example of a PR that is a fork and what a user would see if they tried to run the workflow

      # User forks the repo and creates a PR to the dev branch
      # If the PR is a fork, we need to cancel the workflow and comment on the PR
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check if PR is a fork
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "This workflow does not run on forks, and requires a review before being merged into a branch for testing and secondary or final review."
          exit 1

      - name: Get Changed Demos
        id: changed_demos
        uses: ./.github/actions/get-changed-demos/action.yml
        with:
          json: true
      
      - name: Build
        uses: ./.github/workflows/v2-build-demos.yml
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          demo-names: ${{ steps.changed_demos.outputs.updated }}
          dev: ${{ github.event.pull_request.base.ref == 'dev' }}
          save-artifact: true
          artifact-name: demo-build-${{ github.event.pull_request.head.sha }}
          keep-going: false
          quiet: false
          batch_size: 10
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.base.ref == 'dev' || github.event.pull_request.base.ref == 'master'
    steps:
      # Pseudo code for deploying the demos — echos
      - name: Upload demos
        run: |
          echo "Deploying demos to the server"
      
      - name: Post comment of preview link (Maybe?)
        run: |
          echo "Post a comment on the PR with the link to the preview"
          echo "Comment posted on PR with preview link"
          echo of all the demos that were built and their links