name: Build and Deploy V2 Demos
on:
  push:
    branches:
      - sc-79849-implement-improved-demo-build-pipeline

jobs:
  build:
    uses: ./.github/workflows/v2-build-demos.yml
    with:
      ref: ${{ github.ref }}
      demo-names: 'covalent_cloud_gpu gbs'
      save-artifact: true
      keep-going: false

  deploy:
    needs: build
    uses: ./.github/workflows/v2-deploy-demos.yml
    with:
      environment: swc-dev
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      preview: false
      branch: ${{ github.ref }}
    secrets: inherit
