name: V2 Build PR

on:
  pull_request:
    # The branches setting determines which branches the workflow will run on.
    branches: [master, dev]

permissions:
  contents: read

concurrency:
  group: build-v2-demos-${{ github.event.pull_request.head.sha }}
  cancel-in-progress: true

jobs:
  identify-changed-demos:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.get-changed-demos.outputs.updated }}
      deleted: ${{ steps.get-changed-demos.outputs.deleted }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed demos
        id: get-changed-demos
        uses: ./.github/actions/get-changed-demos

      - name: Output changed demos
        run: |
          echo "Updated Demos: ${{ steps.get-changed-demos.outputs.updated }}"
          echo "Deleted Demos: ${{ steps.get-changed-demos.outputs.deleted }}"

      - name: Exit if no changes
        if: steps.get-changed-demos.outputs.updated == ''
        run: |
          echo "No changes found in demos. Exiting workflow."
          exit 1

  build-updated-demos:
    uses: ./.github/workflows/v2-build-demos.yml
    needs: identify-changed-demos
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      demo-names: ${{ needs.identify-changed-demos.outputs.updated }}
      dev: ${{ github.event.pull_request.base.ref == 'dev' }}
      save-artifact: true
      artifact-name: demo-build-${{ github.event.pull_request.head.sha }}
      keep-going: false
      quiet: false
      batch_size: 10

  save-pr-info:
    runs-on: ubuntu-latest
    needs: [identify-changed-demos, build-updated-demos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Save PR info
        id: save-pr-info
        run: |
            echo "Saving PR info to artifact"
            mkdir -p pr-info
            echo "{
            \"pr_number\": \"${{ github.event.pull_request.number }}\",
            \"slugs\": [$(echo '${{ needs.identify-changed-demos.outputs.updated }}' | sed 's/ /", "/g' | sed 's/^/"/' | sed 's/}$/}/')]
            }" > pr-info/pr-info.json
            echo "PR info saved to pr-info/pr-info.json"

      - name: Upload PR info
        uses: actions/upload-artifact@v4
        with:
          name: pr-info
          path: pr-info/pr-info.json