name: V2 Build PR

on:
  pull_request:
    # The branches setting determines which branches the workflow will run on.
    branches: [master, dev]

permissions:
  contents: read

concurrency:
  group: build-v2-demos-${{ github.event.pull_request.head.sha }}
  cancel-in-progress: true

jobs:
  identify-changed-demos:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.get-changed-demos.outputs.updated }}
      deleted: ${{ steps.get-changed-demos.outputs.deleted }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed demos
        id: get-changed-demos
        uses: ./.github/actions/get-changed-demos

      - name: Output changed demos
        run: |
          echo "Updated Demos: ${{ steps.get-changed-demos.outputs.updated }}"
          echo "Deleted Demos: ${{ steps.get-changed-demos.outputs.deleted }}"

      - name: Exit if no changes
        if: steps.get-changed-demos.outputs.updated == ''
        run: |
          echo "No changes found in demos. Exiting workflow."
          exit 1

  build-updated-demos:
    uses: ./.github/workflows/v2-build-demos.yml
    needs: identify-changed-demos
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      demo-names: ${{ needs.identify-changed-demos.outputs.updated }}
      dev: ${{ github.event.pull_request.base.ref == 'dev' }}
      save-artifact: true
      artifact-name: demo-build-${{ github.event.pull_request.head.sha }}
      keep-going: false
      quiet: false
      batch_size: 10
  
  # If successful, save the PR number to a artifact called demo-build-pr-number
  upload:
    needs: build-updated-demos
    runs-on: ubuntu-latest
    steps:
      - name: Save Demo Build PR Number
        id: save-pr-number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/

      - name: Print PR Number from Artifact
        id: print-pr-number
        run: |
          echo "PR Number: ${{ steps.save-pr-number.outputs.PR_NUMBER }}"
          echo "PR Number from Artifact: $(cat ./pr/pr_number)"
          echo "PR Number from Artifact (without quotes): $(cat ./pr/pr_number | tr -d '\"')"
          echo "PR Number from Artifact (without quotes): ${{ steps.save-pr-number.outputs.PR_NUMBER }}"
          