name: V2 Deploy PR

# EXAMPLE ARTIFACT FOR build-info.txt
# PR_NUMBER=1
# UPDATED_DEMOS=gbs-copy gbs
# DELETED_DEMOS=
# BUILD_ID=14603073095
# BRANCH=test-build-deploy-trigger
# COMMIT_SHA=7fb5b4332416825c4ce55ea3fe275a941be7f6aa
# COMMIT_MESSAGE=create copy for testing purpose
# COMMIT_URL=https://github.com/Alan-eMartin/qml/pull/1

on:
  workflow_run:
    workflows:
      - "V2 Build PR"
    types:
      - completed

permissions:
  actions: read
  pull-requests: write # Required to post comments
  contents: read

concurrency:
  group: deploy-v2-demos-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  retrieve-build-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Info Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-info
          path: pr-info.txt

      - name: Extract Build Info
        id: extract-build-info
        run: |
          echo "PR_NUMBER=$(grep 'PR_NUMBER' build-info.txt | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "UPDATED_DEMOS=$(grep 'UPDATED_DEMOS' build-info.txt | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "COMMIT_SHA=$(grep 'COMMIT_SHA' build-info.txt | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Create PR comment
        id: create-pr-comment
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}
          UPDATED_DEMOS: ${{ env.UPDATED_DEMOS }}
          COMMIT_SHA: ${{ env.COMMIT_SHA }}
        run: |
          echo "Creating PR comment for PR #${{ env.PR_NUMBER }}"
          echo "## Build Info" > pr-comment.md
          echo "### Updated Demos" >> pr-comment.md
          echo "<details>" >> pr-comment.md
          echo "<summary>Click to see all demo previews</summary>" >> pr-comment.md
          echo "" >> pr-comment.md
          IFS=' ' read -r -a demos <<< "${{ env.UPDATED_DEMOS }}"
          for demo in "${demos[@]}"; do
            echo "- [${demo}](https://pennylane.ai/qml/demos/${demo}?preview=true)" >> pr-comment.md
          done
          echo "</details>" >> pr-comment.md

      - name: Comment on PR
        uses: XanaduAI/cloud-actions/create-and-update-pull-request-comment@main
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}
        with:
          github_token: ${{ github.token }}
          pull_request_number: ${{ env.PR_NUMBER }}
          comment_body: $(cat pr-comment.md)
